# Tiltfile for using live_update with example Python Flask app

# To deploy to a non-local cluster, you'll need to tell Tilt what registry to use.
# Uncomment the line below, and replace 'gcr.io/example' with your registry
# default_registry('gcr.io/example')

k8s_yaml('hello.yaml')

docker_build('hello-image', './hello',
  live_update=[
    # hello/requirements.txt is the list of dependencies
    # we don't want the container running in the cluster to download everything,
    # so fall back to an image build
    fall_back_on('hello/requirements.txt'),
    sync('./hello', '/'),
  ])

k8s_resource('hello', port_forwards=5000)
